version: '3.9'

services:
  app-test:
    build:
      context: .
      dockerfile: test.Dockerfile
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
      - ./database.sqlite:/usr/src/app/database.sqlite
    ports:
      - 3000:3000
    stdin_open: true
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
